#!/usr/bin/env bash
databases=`psql --username=postgres -l | awk '{ print $1}' | sed '/^|/ d' | sed '1,3d' | head -n -2 | grep -Ev "^(postgres|template0|template1)$"`
pg_dump --username=postgres -b -d ${databases} | restic backup --stdin --stdin-filename postgres.sql ${1}
# the ${1} allows to pass additional arguments to restic

# NOTE that stream_pg_dump expects to be run as the postgres user. On shell, 
# you can do this with su -c "./stream_pg_dump" postgres
