#!/usr/bin/env bash
databases=`/usr/bin/mysql -e "SHOW DATABASES;" | grep -Ev "^(Database|mysql|sys|information_schema|performance_schema)$"`
/usr/bin/mysqldump --single-transaction --triggers --events --routines --skip-dump-date -B ${databases} | /usr/local/bin/restic backup --stdin --stdin-filename mysql.sql ${1}
# the ${1} allows to pass additional arguments to restic
